### ISSUE TITLE
Some errors for Roles

### ISSUE THREAD

**Issue by kulkaGM** [archie426/RocketModToOpenMod#3]
When we use "RocketModToOpenMod" is generate Roles for OpenMod
like that:

```
roles:
- id: Default
  priority: 0
  parents:
  - 
  permissions:
  - RocketMod.PermissionLinkbalance
  - RocketMod.PermissionLinkcost
  - RocketMod.PermissionLinksell
  displayName: Default
  data: {}
  isAutoAssigned: false
```

In permissions missing ':' after 'PermissionLink'

And 'isAutoAssigned' must be 'true' for default Role

'RocketMod' prefix is bad prefix and must be rewrited to 'Rocket'

```
roles:
- id: Default
  priority: 0
  parents:
  - 
  permissions:
  - Rocket.PermissionLink:balance
  - Rocket.PermissionLink:cost
  - Rocket.PermissionLink:sell
  displayName: Default
  data: {}
  isAutoAssigned: true
```
